config:
  name: arch-order-configmap
  port: 8000
  ddl: validate
secret:
  name: arch-order-secret
deployment:
  app:
    image: zsalamandra/ex08-order
    port: 8000
    replicas: 2
  db:
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: arch-order-service
    type: NodePort
    protocol: TCP
    port: 9000
  db:
    name: postgresql-order-service
    host: "postgresql-order-service"
    type: ClusterIP
    port: 5432
    sport: "5432"
    dbname: arch_order_db
    dbschema: public
redis:
  name: redis-order
ingress:
  name: otus-hw06-ingress
  host: arch.homework