apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: dadaev-arch-otus
data:
  SERVER_PORT: "{{ .Values.config.port }}"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "{{ .Values.config.ddl }}"