config:
  name: arch-profiles-configmap
  port: 8000
  ddl: validate
secret:
  name: arch-profiles-secret
deployment:
  app:
    type: NodePort
    image: zsalamandra/ex-05-user-service-dzm
    port: 8000
    replicas: 1
  db:
    type: NodePort
    image: postgres:latest
    port: 5432
    replicas: 1
service:
  app:
    name: arch-profiles-service
    type: NodePort
    protocol: TCP
    port: 9000
  db:
    name: postgresql-profiles-service
    host: "postgresql-profiles-service"
    type: NodePort
    port: 5432
    sport: "5432"
    dbname: arch_profiles_db
    dbschema: public
