apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: ex03-dadaev
  template:
    metadata:
      labels:
        app: ex03-dadaev
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: ex03-config
                  key: SERVER_PORT
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ex03-config
                  key: DATASOURCE_URL
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ex03-config
                  key: DATABASE_USER
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ex03-secret
                  key: POSTGRES_PASSWORD
