apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.config.namespace}}
  name: {{ include "ex03.fullname" . }}
  labels:
    {{- include "ex03.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "ex03.selectorLabels" . | nindent 4 }}
