apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: dadaev-arch-otus
type: Opaque
data:
  DATABASE_NAME: {{ .Values.service.db.dbname | b64enc }}
  DATABASE_URL: {{ printf "jdbc:postgresql://%s:%s" .Values.service.db.host .Values.service.db.sport | b64enc }}
  DATABASE_SCHEMA: {{ .Values.service.db.dbschema | b64enc }}
  SPRING_DATASOURCE_USERNAME: YWRtaW4=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
