apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: dadaev-arch-otus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /otusapp/zsalamandra/orders/?(.*)($|/)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.app.name }}
                port:
                  number: {{ .Values.service.app.port }}
          - path: /orders/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.app.name }}
                port:
                  number: {{ .Values.service.app.port }}
          - path: /otusapp/zsalamandra/orders/actuator/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.app.name }}
                port:
                  number: 9099
          - path: /orders/actuator/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.app.name }}
                port:
                  number: 9099