kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: dadaev-arch-otus
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
