controller:
  kind: DaemonSet
  extraArgs:
    metrics-per-host: false
  reportNodeInternalIp: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: NodePort